# Generated by Django 4.2.10 on 2025-08-25 17:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications_included', models.JSONField(blank=True, default=list)),
                ('postoperative_care', models.JSONField(blank=True, default=list)),
                ('hospital_stay_nights', models.IntegerField(default=0)),
                ('special_equipment', models.JSONField(blank=True, default=list)),
                ('dietary_plan', models.BooleanField(default=False)),
                ('additional_services', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_email', models.CharField(blank=True, max_length=200, null=True)),
                ('procedure_name', models.CharField(max_length=200)),
                ('procedure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('procedure_description', models.TextField(blank=True, null=True)),
                ('surgeon_name', models.CharField(blank=True, max_length=200, null=True)),
                ('surgeon_specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('surgery_duration_hours', models.IntegerField(default=0)),
                ('anesthesia_type', models.CharField(blank=True, max_length=200)),
                ('additional_equipment', models.JSONField(blank=True, default=list)),
                ('additional_materials', models.JSONField(blank=True, default=list)),
                ('is_ambulatory', models.BooleanField(default=True)),
                ('hospital_nights', models.IntegerField(default=0)),
                ('facility_fee', models.FloatField(default=0.0)),
                ('equipment_costs', models.FloatField(default=0.0)),
                ('anesthesia_fee', models.FloatField(default=0.0)),
                ('other_costs', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=200)),
                ('status', models.CharField(default='borrador', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('surgical_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.surgicalpackage')),
            ],
        ),
    ]
