# Generated by Django 5.2.5 on 2025-08-21 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(help_text='ID legible para la cotización, ej: Q-2025-001', max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateField()),
                ('procedure_date', models.DateField()),
                ('hospital', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=255)),
                ('total_suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_packages', to='quotes.quote')),
            ],
        ),
    ]
